### ISSUE TITLE
Fetch error

### ISSUE THREAD

**Issue by sollevix67** [VoidRunner87/mydu_pve_mod#5]
Got an error when trying to access http://localhost:8080/swagger/index.html :

```
Errors
Fetch error
Internal Server Error http://localhost:8080/swagger/v1/swagger.json
```

I'm running voidrunner7891/dynamic_encounters:lates on Docker

**Comment by VoidRunner87** [comment]
Thank you for the report. Fixed in main

**Comment by Zedvets** [comment]
I have the same issue using the latest. removed IP below.

Fetch error
Internal Server Error http://xx.xx.xx.84:8080/swagger/v1/swagger.json

**Comment by mike-leo001** [comment]
I also have this error. Any solutions?

**Comment by VoidRunner87** [comment]
Is it still happening with the latest?
I only saw these messages now... but someone pinged me. and I fixed it.

**Comment by Zedvets** [comment]
This issue is fixed for me, but I can't seem to get the mod to work. No pirate ships are spawning.
